theme: jekyll-theme-slate
title: Andria Emmons
description:
  Business Analyst - experienced in performing detailed requirements analysis, documenting processes, leading projects comprised of both technical and non-technical users.
  
  Master Data Analyst - experienced using SQL, Python, SAS Studio, R, advanced Excel, MS Access certified. Analytical thinker with the ability to grasp complex challenges.
  
